on:
  push:
    branches:
      - develop
name: 🛠 DEV Deploy
jobs:
  deploy_to_dev:
    name: 🛠 DEV Deploy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    environment: developement
    steps:
    - name: 🚚 Get latest dev code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files on DEV Environment
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ vars.SERVER_DIR }}
